#!/bin/bash
set -euo pipefail

rm -rf build
mkdir build

cd src
version="$(jq -r '.version' manifest.json)"
package="zotcardx-${version}.xpi"
zip -r "../build/${package}" *
cd ../build

hash="$(shasum -a 256 "${package}" | cut -d' ' -f1)"
jq --arg hash "sha256:${hash}" '.addons["zotcard@zotero.org"].updates[0].update_hash = $hash' ../updates.json.tmpl > ../updates.json
